apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-clientapp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      service: obs-clientapp
  template:
    metadata:
      labels:
        type: frontend
        service: obs-clientapp
    spec:
      containers:
        - name: container
          image: thayalangr/obs-clientapp:production
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: obs-clientapp
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    type: frontend
    service: obs-clientapp