apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellerspot-poc-core-app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      service: sellerspot-poc-core-app
  template:
    metadata:
      labels:
        type: frontend
        service: sellerspot-poc-core-app
    spec:
      containers:
        - name: container
          image: thayalangr/sellerspot-poc-core-app
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: sellerspot-poc-core-app
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    type: frontend
    service: sellerspot-poc-core-app
