apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: grthayalan18@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudflare:
          email: ledger.sellerspot@gmail.com
          apiTokenSecretRef:
            name: sellerspotdev.tech-cloudflare-api-token-secret
            key: api-token